language: ruby
rvm:
    - 2.1
    - 2.2
    - 2.3
    - 2.4.0
    - ruby-head
sudo: required
before_install:
    - gem update --system
    - gem install bundler -v '1.15.4'
    - bundler --version
install:
    - bundler install
    - ./bin/dev_setup.sh
    - gem build thefox-wallet.gemspec
    - gem install thefox-wallet-*.gem
    - gem list -l thefox-wallet
script:
    - ./bin/test.sh
    - cd
    - which -a wallet
