language: ruby
rvm:
    - 2.1
    - 2.2
    - 2.3
    - 2.4.0-preview2
    - ruby-head
sudo: required
before_install:
    - gem update --system
    - gem install bundler -v '~>1.13'
    - bundler --version
install:
    - make
    - gem build thefox-wallet.gemspec
    - gem install thefox-wallet-*.gem
    - gem list -l thefox-wallet
script:
    - make test
    - cd
    - which -a wallet
